    "__kernel void hello_kernel(__global int* buffer, int n) {\n"
    "   if (get_global_id(0) % 3 == 0) {\n"
    "       buffer[get_global_id(0)] = 2;\n"
    "   } else if(get_global_id(0) % 3 == 1) {\n"
    "       buffer[get_global_id(0)] = 3;\n"
    "   } else {\n"
    "       buffer[get_global_id(0)] = 5;\n"
    "   }\n"
    "}\n"